# POST

POST http://127.0.0.1:9900/form
Content-Type: multipart/form-data; boundary=xxx

--xxx
Content-Disposition: form-data; name="username"

linonon
--xxx
Content-Disposition: form-data; name="password"

123
--xxx--