@startuml webpwd

participant Server order 1
participant Client order 2
participant DNS order 3
Client -> DNS: Send URL
Client <- DNS: IP address
Server <-> Client: TCP connection
Client -> Server: Http Request
Server -> Client: Http Response
Server x<->x Client: Disconnect

@endum